export default [
  {
    id: 1,
    url: "https://products1.imgix.drizly.com/ci-wyders-pear-cider-9abbf293f5123aed.png",
    name: "Wyder's Pear Cider",
    category: "Perry",
    description: "Perry/5% ABV",
    price: 1999,
  },
  // {
  //   id: 2,
  //   url: "https://products2.imgix.drizly.com/ci-twisted-tea-e8229db6564a7dd5.jpeg",
  //   name: "Twisted Tea Original",
  //   category: "Hard Iced Tea",
  //   description: "Hard Iced Tea /5% ABV / United States",
  //   price: 2599,
  // },
  {
    id: 2,
    url: "https://products3.imgix.drizly.com/ci-corona-light-f8145b655e34017f.jpeg",
    name: "Corona Light",
    category: "Light Lager",
    description: "Light Lager /4% ABV / Mexico",
    price: 50000,
  },
  {
    id: 3,
    url: "https://products2.imgix.drizly.com/ci-guinness-draught-420c95ffc7f4bdc0.jpeg",
    name: "Guinness Draught",
    category: "Dry Stout",
    description: "Dry Stout /4.2% ABV / Ireland",
    price: 4000,
  },
  {
    id: 4,
    url: "https://products1.imgix.drizly.com/ci-sierra-nevada-hazy-ipa-1ae41056d225af7c.jpeg?",
    name: "Sierra Nevada Hazy",
    category: "Craft, Independent Craft Brewer",
    description: "Ale /6.7% ABV / California, United States",
    price: 2000,
  },
  {
    id: 5,
    url: "https://products1.imgix.drizly.com/ci-new-belgium-rampant-imperial-ipa-ac5c14076f11a6c8.jpeg",
    name: "Vodoo  Ranger Imperial",
    category: "Imperial",
    description: "Imperial / Double IPA /9% ABV / United States",
    price: 100,
  },
  {
    id: 6,
    url: "https://products3.imgix.drizly.com/ci-white-claw-black-cherry-hard-seltzer-811a20d37c818a83.jpeg",
    name: "Hard Seltzer",
    category: "Hard Seltzer /5% ABV / Illinois, United States",
    description: "Imperial / Double IPA /9% ABV / United States",
    price: 100,
  },
  {
    id: 7,
    url: "https://products3.imgix.drizly.com/ci-busch-light-7e32f272e102c773.jpeg",
    name: "Busch Light",
    category: "Light",
    description: "Light Lager /4.1% ABV / Missouri, United States",
    price: 100,
  },
];
